### PR TITLE
feat(scaleway): add scaleway pricing

### PR DESCRIPTION
**Pull request by adnsio**
*WIP*

Add Scaleway.com pricing

### CODE REVIEW

**Comment by aliscott** [comment]
Thanks for adding this @adnsio! Let me know when this is ready for review and I'll take a look 😄

**Comment by alikhajeh1** [comment]
@adnsio just wanted to say thanks for chipping away at this :)

**Comment by adnsio** [comment]
@alikhajeh1 I have a question. Since Scaleway doesn't have an official API where it publishes the pricing of its services, what should I do? I was thinking of creating an object with the current pricing of the services (for example the load balancer, object storage, etc..). WDYT?

**Comment by alikhajeh1** [comment]
hmm that's a tough done since that price json/yaml would need to be kept uptodate manually, do you know if they have a json object they use on their marketing site that we could fetch? This is what AWS had ~10 years ago when I started looking at their pricing, no APIs... or maybe we should email them to see if they have anything more structured we can use?

Or maybe I'm over-thinking this as I counted a total of around 50 price points on their marketing site (no per-region pricing?) so a hard-coded object is ok just now. 

@aliscott any thoughts?

**Comment by aliscott** [comment]
The pricing page loads it from this JSON (https://www.scaleway.com/page-data/en/pricing/page-data.json), but it seems to be more of a generic format for displaying a page than actually defining prices. I think hard-coded is probably the way to go if it's going to be a challenge to scrape nicely. Although I wonder if we can get notified when the pricing page changes so we can update them.

cc @remyleone (Scaleway) if he has any ideas about getting structured pricing data from Scaleway to use in Infracost.

**Comment by alikhajeh1** [comment]
@adnsio please see https://www.infracost.io/blog/jul-2021-update as we’ve made significant changes to the Cloud Pricing API. We’d still love to support Scaleway but it seems best if we close this PR so a new one can be opened. Please let us know if we can help.

**Comment by adnsio** [comment]
@alikhajeh1 yeah I've read it yesterday. I will open a new PR with hard-coded prices until they release an API to fetchar them.

**Comment by alikhajeh1** [comment]
Thank you @adnsio!

**Pull request closed without merging**
